config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'welcome#index'

  get '/register', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # resources :merchants, except: [:destroy]
  get '/merchants', to: 'merchants#index'
  get '/merchants/new', to: 'merchants#new'
  post '/merchants', to: 'merchants#create'
  get '/merchants/:id', to: 'merchants#show', as: 'merchant'
  get '/merchants/:id/edit', to: 'merchants#edit'
  patch '/merchants/:id', to: 'merchants#update'


  get '/merchants/:merchant_id/items', to: 'merchant_items#index'

  # resources :items, only: %i[index show] do
    # resources :reviews, only: %i[new create]
  # end
  get '/items', to: 'items#index', as: 'item'
  get '/items/:id', to: 'items#show'
  get '/items/:item_id/reviews/new', to: 'reviews#new'
  post '/items/:item_id/reviews', to: 'reviews#create'

  namespace :profile do
    get '/', to: 'users#show'
    get '/edit', to: 'users#edit'
    patch '/user', to: 'users#update'
    get '/edit/pw', to: 'security#edit'
    patch '/user/pw', to: 'security#update'

    # resources :orders, only: [:index, :show, :new, :create, :update]
    get '/orders', to: 'orders#index'
    get '/orders/new', to: 'orders#new'
    post '/orders', to: 'orders#create'
    get '/orders/:id', to: 'orders#show', as: 'order'
    patch '/orders/:id', to: 'orders#update'
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/users/:id/orders', to: 'user_orders#index'
    get '/users/:id/orders/:id', to: 'user_orders#show'
    patch '/users/:id/orders/:id', to: 'user_orders#update'
    get '/merchants/:id/orders/:id', to: 'merchant_orders#show'

    # resources :users, only: %i[index show]
    get '/users', to: 'users#index'
    get '/users/:id', to: 'users#show', as: 'user'

    # resources :orders, only: [:update]
    patch '/orders/:id', to: 'orders#update'

    # resources :merchants, only: %i[index show update]
    get '/merchants', to: 'merchants#index'
    get '/merchants/:id', to: 'merchants#show', as: 'merchant'
    patch '/merchants/:id', to: 'merchants#update'
  end

  namespace :merchant do
    get '/', to: 'dashboard#index'
    get '/:merchant_id/items/new', to: 'items#new'
    post '/:merchant_id/items', to: 'items#create'
    patch '/items/:id/toggle', to: 'toggle#update'

    # resources :items, only: %i[index show edit update destroy]
    get '/items', to: 'items#index'
    get '/items/:id', to: 'items#show', as: 'item'
    get '/items/:id/edit', to: 'items#edit'
    patch '/items/:id', to: 'items#update'
    delete '/items/:id', to: 'items#destroy'

    # resources :orders, only: [:show]
    get '/orders/:id', to: 'orders#show', as: 'order'

    # resources :item_orders, only: [:update]
    patch '/item_orders/:id', to: 'item_orders#update', as: 'item_order'

    # resources :discounts, only: [:index, :show, :new, :create, :update]
    get '/discounts', to: 'discounts#index'
    get '/discounts/new', to: 'discounts#new'
    post '/discounts', to: 'discounts#create'
    get '/discounts/:id', to: 'discounts#show', as: 'discount'
    patch '/discounts/:id', to: 'discounts#update'
  end

  # resources :reviews, only: [:edit, :update, :destroy]
  get '/reviews/:id/edit', to: 'reviews#edit'
  patch '/reviews/:id', to: 'reviews#update'
  delete '/reviews/:id', to: 'reviews#destroy'

  post '/cart/:item_id', to: 'cart#add_item'
  get '/cart', to: 'cart#show'
  delete '/cart', to: 'cart#empty'
  delete '/cart/:item_id', to: 'cart#remove_item'
  patch '/cart/:item_id', to: 'cart#edit'

  # resources :orders, only: [:new, :create, :show]
  get '/orders/new', to: 'orders#new'
  post '/orders', to: 'orders#create'
  post '/orders/:id', to: 'orders#show'
end

app/models/item.rb
class Item <ApplicationRecord
  belongs_to :merchant
  has_many :reviews, dependent: :destroy
  has_many :item_orders
  has_many :orders, through: :item_orders
  has_many :discounts, through: :merchant

  validates_presence_of :name,
                        :description,
                        :price,
                        :image,
                        :inventory
  validates_inclusion_of :active?, :in => [true, false]
  validates_numericality_of :price, greater_than: 0
  validates_numericality_of :inventory, greater_than: 0, less_than_or_equal_to: 999999

  def self.popular(limit, order)
    left_outer_joins(:item_orders)
      .group(:id)
      .order("COALESCE(SUM(quantity), 0) #{order}, items.id")
      .limit(limit)
  end

  def average_review
    reviews.average(:rating)
  end

  def sorted_reviews(limit, order)
    reviews.order(rating: order).limit(limit)
  end

  def no_orders?
    item_orders.empty?
  end

  def quantity_bought
    item_orders.sum(:quantity)
  end

  def best_discount(quantity)
    discounts
      .where("status = 1 AND requirement <= #{quantity}")
      .order(percent_off: :desc)
      .take
  end

  def modified_price(quantity)
    discount = best_discount(quantity)
    if discount
      price - (price * (discount.percent_off.to_f / 100))
    else
      price
    end
  end

end

app/models/merchant.rb
class Merchant <ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :item_orders, through: :items
  has_many :orders, through: :item_orders
  has_many :users
  has_many :discounts

  validates_presence_of :name,
                        :address,
                        :city,
                        :state,
                        :zip


  def no_orders?
    item_orders.empty?
  end

  def item_count
    items.count
  end

  def average_item_price
    items.average(:price)
  end

  def distinct_cities
    item_orders.joins(:order).order('orders.city asc').distinct.pluck('orders.city')
  end

  def active_items
    items.where(active?: true).order(:id)
  end

  def pending_orders
    orders.where("orders.status = 1").distinct
  end

end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController

  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end

  def update
    merchant = Merchant.find(params[:id])
    merchant.toggle!(:active?)
    if !merchant.active?
      merchant.items.update_all(active?: false)
      flash[:success] = "#{merchant.name} has been deactivated."
    else
      merchant.items.update_all(active?: true)
      flash[:success] = "#{merchant.name} has been activated."
    end
    redirect_to admin_merchants_path
  end
end

app/controllers/items_controller.rb
class ItemsController<ApplicationController

  def index
    @items = Item.where(active?: true)
  end

  def show
    @item = Item.find(params[:id])
    render file: "/public/404" unless viewable
  end

  private

    def viewable
      return current_admin? if !@item.active?
      true
    end
end

app/controllers/merchant/base_controller.rb
class Merchant::BaseController < ApplicationController
  before_action :require_merchant

  def require_merchant
    render file: "/public/404" unless current_merchant?
  end
end

app/controllers/merchant/dashboard_controller.rb
class Merchant::DashboardController < Merchant::BaseController

  def index
    @merchant = current_user.merchant
  end
end

app/controllers/merchant/discounts_controller.rb
class Merchant::DiscountsController < Merchant::BaseController
  def index
    @merchant = current_user.merchant
  end

  def new
    @discount = Discount.new
  end

  def show
    @discount = Discount.find(params[:id])
  end

  def create
    discount = current_user.merchant.discounts.create(discount_params)
    if discount.save
      flash[:success] = "Discount successfully created."
      redirect_to merchant_discounts_path
    else
      error_message(discount)
      @discount = discount
      render :new
    end
  end

  def update
    discount = Discount.find(params[:id])
    discount.update(status: 0)
    redirect_to merchant_discounts_path
  end

  private

    def discount_params
      params.require(:discount).permit(:percent_off, :requirement)
    end
end

app/controllers/merchant/item_orders_controller.rb
class Merchant::ItemOrdersController < Merchant::BaseController
  def update
    item_order = ItemOrder.find(params[:id])
    if item_order.unfulfilled? && item_order.fulfill
      flash[:success] = "Item has been fulfilled."
      item_order.order.ready
    else
      flash[:error] = "Cannot fulfill order."
    end
    redirect_to(merchant_order_path(item_order.order.id))
  end
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < Merchant::BaseController
  before_action :require_employee, only: [:new, :create]
  before_action :require_item_match, only: [:show, :edit, :update]

  def index
    @items = Merchant.find(current_user.merchant.id).items
  end

  def new
    merchant = Merchant.find(params[:merchant_id])
    @item = merchant.items.create(item_params)
  end

  def create
    merchant = Merchant.find(params[:merchant_id])
    params.delete :image if params[:image].blank?
    @item = merchant.items.create(item_params)
    if @item.save
      flash[:success] = "#{@item.name} has been saved."
      redirect_to "/merchant/items"
    else
      flash.now[:error] = @item.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash[:success] = "#{@item.name} has been updated."
      redirect_to "/merchant/items"
    else
      flash.now[:error] = @item.errors.full_messages.to_sentence
      render :edit
    end
  end

  def show
  end

  def destroy
    item = Item.find_by(id: params[:id])
    if !item
      flash[:error] = "Item already deleted."
    elsif item.no_orders?
      flash[:success] = "'#{item.name}' has been deleted."
      item.destroy
    else
      flash[:error] = "Cannot delete an item with orders."
    end
    redirect_to "/merchant/items"
  end

    private

    def item_params
      params.permit(:name,:description,:price,:inventory,:image)
    end

    def require_employee
      authorized = params[:merchant_id] == current_user.merchant.id.to_s
      render file: "/public/404" unless authorized
    end

    def require_item_match
      @item = Item.find_by(id: params[:id])
      authorized = @item && @item.merchant == current_user.merchant
      render file: "/public/404" unless authorized
    end
end

app/controllers/merchant/orders_controller.rb
class Merchant::OrdersController < Merchant::BaseController
  before_action :require_orders, only: [:show]

  def show
  end

  private
    def require_orders
      @order = Order.find_by(id: params[:id])
      no_orders = @order.nil? || @order.item_orders.by_merchant(current_user.merchant.id).empty?
      render file: "/public/404" if no_orders
    end
end

app/controllers/merchant/toggle_controller.rb
class Merchant::ToggleController < Merchant::BaseController

  def update
    item = Item.find(params[:id])
    item.toggle!(:active?)
    if item.active?
      flash[:success] = "#{item.name} is now available for sale."
    else
      flash[:error] = "#{item.name} is no longer for sale."
    end
    redirect_to "/merchant/items"
  end
end

app/controllers/merchants_controller.rb
class MerchantsController <ApplicationController

  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end

  def new
  end

  def create
    merchant = Merchant.create(merchant_params)
    if merchant.save
      redirect_to merchants_path
    else
      flash[:error] = merchant.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @merchant = Merchant.find(params[:id])
  end

  def update
    @merchant = Merchant.find(params[:id])
    @merchant.update(merchant_params)
    if @merchant.save
      redirect_to "/merchants/#{@merchant.id}"
    else
      flash[:error] = @merchant.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def merchant_params
    params.permit(:name,:address,:city,:state,:zip)
  end

end

app/views/merchant/items/edit.html.erb
<h1>Edit <%=link_to @item.name, "/items/#{@item.id}" %></h1>
<center>
  <%= form_tag "/merchant/items/#{@item.id}", method: :patch  do %>
    <%= label_tag :name %>
    <%= text_field_tag :name, "#{@item.name}"%>

    <%= label_tag :description %>
    <%= text_field_tag :description, "#{@item.description}" %>

    <%= label_tag :price %>
    <%= text_field_tag :price, "#{@item.price}" %>

    <%= label_tag :image %>
    <%= text_field_tag :image, "#{@item.image}" %>

    <%= label_tag :inventory %>
    <%= number_field_tag :inventory, "#{@item.inventory}" %>

    <%= submit_tag 'Update Item' %>
  <% end %>
</center>

app/views/merchant/items/index.html.erb
<h1>My Items - <%= link_to current_user.merchant.name, merchant_path(current_user.merchant.id) %></h1>
<p align="center"><%= link_to "Add New Item", "/merchant/#{current_user.merchant.id}/items/new" %></p>

<section class="grid-container">
  <% @items.each do |item| %>
    <section class = "grid-item" id= 'item-<%=item.id%>'>
      <%= render partial: '/partials/item_info', locals: {item: item, path: merchant_item_path(item.id)}%>
      <% if item.active? %>
        <p>
          Active -
          <%= link_to "Deactivate", "/merchant/items/#{item.id}/toggle", method: :patch %>
        </p>
      <% else %>
        <p>
          Inactive -
          <%= link_to "Activate", "/merchant/items/#{item.id}/toggle", method: :patch %>
        </p>
      <% end %>
      <%= link_to "Edit", "/merchant/items/#{item.id}/edit", method: :get %>
      <%= link_to "Delete", "/merchant/items/#{item.id}", method: :delete %>
    </section>
  <% end %>
</section>

app/views/merchant/items/new.html.erb
<h1>Create New Item For <%=link_to @item.merchant.name, "/merchants/#{@item.merchant.id}" %></h1>

<center>
  <%= form_tag "/merchant/#{@item.merchant.id}/items", method: :post do %>
    <%= label_tag :name %>
    <%= text_field_tag :name, @item.name %>

    <%= label_tag :description %>
    <%= text_field_tag :description, @item.description %>

    <%= label_tag :price %>
    <%= text_field_tag :price, @item.price %>

    <%= label_tag :image %>
    <%= text_field_tag :image, @item.image %>

    <%= label_tag :inventory %>
    <%= text_field_tag :inventory, @item.inventory %>

    <%= submit_tag 'Create Item' %>
  <% end %>
</center>

app/views/merchant/items/show.html.erb
<h1><%= link_to @item.name, "/items/#{@item.id}" %></h1>
<p align="center">Sold by: <%=link_to @item.merchant.name, "/merchants/#{@item.merchant.id}" %> </p>
<section align = "center" id = "average-rating">
  <p>Average Rating: <%= @item.average_review %></p>
</section>
<center>
  <section class = "item-show-grid">
    <section class = "item-show-item">
      <img src= <%= @item.image %>>
    </section>
    <section style="text-align:left" class = "item-show-item">
      <p>Description: <%= @item.description %></p>
      <p>Price: <%= number_to_currency(@item.price )%> </p>
      <p>Inventory: <%= @item.inventory %> </p>
      <% if @item.active? %>
        <p style= "color:green">Active</p>
      <% else %>
        <p style= "color:red">Inactive</p>
      <% end %>
      <p><%= link_to "Edit Item", "/merchant/items/#{@item.id}/edit" %></p>
      <p><%= link_to "Delete Item", "/items/#{@item.id}", method: :delete %></p>
      <%= link_to "Add Review", "/items/#{@item.id}/reviews/new" %>
      <%= button_to "Add To Cart", "/cart/#{@item.id}", method: :post %>
    </section>
  </section>
</center>
<center>
<section class = "review-stats">
  <%if @item.reviews.empty? %>
    <h3>This item has not yet been reviewed.</h3>
  <% else %>
    <section class = "top-three-reviews">
      <h2>Top 3 Reviews</h2>
      <% @item.sorted_reviews(3, :desc).each do |review| %>
        <h3><%= "#{review.rating}-#{review.title}" %></h3>
      <% end %>
    </section>
    <section class = "bottom-three-reviews">
      <h2>Bottom 3 Reviews</h2>
      <% @item.sorted_reviews(3, :asc).each do |review| %>
        <h3><%= "#{review.rating}-#{review.title}" %></h3>
      <% end %>
    </section>
  </section>
  <section class = "list-reviews">
    <h2>All Reviews</h2>
    <% @item.reviews.each do |review| %>
      <section id= 'review-<%=review.id%>'>
        <%= review.title %>
        <%= review.content %>
        Rating: <%= review.rating %>/5
        <%= link_to "Edit", "/reviews/#{review.id}/edit" %>
        <%= link_to "Delete", "/reviews/#{review.id}", method: :delete %>
      </section>
    <% end %>
  <% end %>
</section>
</center>